name: Deploy ecosystem

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: next
        required: true
      workflow:
        required: true
        type: choice
        options:
          - cpp
          - web

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-ecosystem:
    runs-on: ubuntu-latest
    steps:
      - uses: Geode-solutions/Versions/deploy-ecosystem@master
        with:
          version: ${{ inputs.branch }}
          token: ${{ secrets.TOKEN }}
          workflow: ${{ inputs.workflow }}
