name: version2

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/github-script@v6
      id: data
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const data = require('./versions.json')
          console.log(data)
          for (const info of data) {
            const {repo} = info
            console.log('Looking for repository:', repo);
            const wf = await github.rest.actions.listWorkflowRuns({
              owner: 'Geode-solutions', 
              repo,
              workflow_id: 'schedule.yml',
              per_page: '1'
            })
            console.log(wf.data.workflow_runs);
            const conclusion = wf.data.workflow_runs[0].conclusion;
            console.log(conclusion);
            const run = await github.rest.actions.getWorkflowRun({
              owner: 'Geode-solutions', 
              repo,
              run_id: wf.data.workflow_runs[0].id
            })
            console.log(run.data.referenced_workflows)
            core.setFailed('Stop');
            if (conclusion != 'success') {
              core.setFailed('Last schedule failed for ' + repo);
              return;
            }
          }
    # - uses: stefanzweifel/git-auto-commit-action@v4
    #   id: commit
    #   with:
    #     commit_message: Apply version changes
    # - name: "Run if changes have been detected"
    #   if: steps.commit.outputs.changes_detected != 'true'
    #   run: exit 1
