name: version

on: 
  push:
  schedule:
    - cron: 0 2 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}
    - uses: Geode-solutions/actions/versions@master
      with:
        repository: OpenGeode;Geode-Common_private
        token: ${{ secrets.TOKEN }}
