name: version2

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  check-next:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.check.outputs.repos }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/github-script@v6
      id: check
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const data = require('./versions.json')
          console.log(data)
          let repos=[]
          for (const info of data) {
            const {repo} = info
            repos.push(repo)
            console.log('Looking for repository:', repo);
            const wf = await github.rest.actions.listWorkflowRuns({
              owner: 'Geode-solutions', 
              repo,
              branch: 'master',
              workflow_id: 'schedule.yml',
              per_page: '1'
              event: 'schedule'
            })
            console.log(wf.data.workflow_runs[0]);
            const conclusion = wf.data.workflow_runs[0].conclusion;
            console.log(conclusion);
            if (conclusion != 'success') {
              core.setFailed('Last schedule failed for ' + repo);
              return;
            }
          }
          core.setOutput('repos', JSON.stringify(repos))

  merge-master:
    runs-on: ubuntu-latest
    needs: check-next
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.check-next.outputs.repos) }}
    steps:
      - run: |
          git remote set-url --push origin https://${{ secrets.TOKEN }}@github.com/Geode-solutions/${{ matrix.repo }}.git
          git remote update
          git fetch
          git checkout origin/next
          git pull origin next
          git checkout --track origin/master
          git pull origin master
          git merge next

        # git push origin master
    # - uses: stefanzweifel/git-auto-commit-action@v4
    #   id: commit
    #   with:
    #     commit_message: Apply version changes
    # - name: "Run if changes have been detected"
    #   if: steps.commit.outputs.changes_detected != 'true'
    #   run: exit 1
